### ISSUE TITLE
米6 点击证书文件提示“没有可安装的证书”

### ISSUE THREAD

**Issue by guchongxi** [wangyongf/blog-mds#1]
如题。

**Comment by wangyongf** [comment]
Hi，你是在通知栏点击的证书吗？

**Comment by wangyongf** [comment]
是不是按照我文章里的步骤走的？卡在哪一步了？

**Comment by wangyongf** [comment]
@GiantZero-x

**Comment by guchongxi** [comment]
1.3，点击证书文件。目前已解决，方法：
* 按照Charles的提示，PC打开 chls.pro/ssl
* 下载得到一个 charles-proxy-ssl-proxying-certificate.pem 证书
* 传送到手机（姿势自选，建议PC开服务让手机访问）
* 下载后会自动打开并要求输入解锁密码（手势），选择vpn和应用即可
